packageExtensions:
  "@parcel/optimizer-image@2.2.1":
    peerDependencies:
      "@parcel/core": ^2.2.1
  "@parcel/reporter-dev-server@2.2.1":
    dependencies:
      "@types/express": ^4.17.13
  "@parcel/transformer-image@2.2.1":
    peerDependencies:
      "@parcel/core": ^2.2.1
  "@parcel/transformer-js@2.2.1":
    peerDependencies:
      "@parcel/core": ^2.2.1
  "@parcel/transformer-postcss@2.2.1":
    dependencies:
      postcss: ^8.1.0
  "@parcel/types@2.2.1":
    dependencies:
      "@parcel/core": ^2.2.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
